name: xiasiyong/utils deploy

on:
  push: #在每次push时执行任务
    branches: [master] #只有在master分支上才会执行
jobs:
  build:
    runs-on: ubuntu-latest #指定构建的虚拟机版本
    steps:
      - name: Checkout #检出
        uses: actions/checkout@main #检出的依赖2
        with:
          persist-credentials: false #不保存证书
        # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: 'https://registry.npmjs.org'
      - name: Cache Node Dependencies #设置依赖缓存.
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.os}}-npm-caches-${{ hashFiles('package-lock.json')}}
      - name: Install Dependencies #安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install --force
      - name: build utils
        run: |
          npm run build
      - name publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

